import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import GradientBackground from "@/components/GradientBackground";
import Hero from "@/components/Hero";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "100",
  variable : "--font-poppins"
})
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "100",
  variable : "--font-monteserrat"
})
export const metadata: Metadata = {
  title: "Stripe | Financial Infrastructure to Grow Your Revenue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      > 
        
        {children}
        
      </body>
    </html>
  );
}
